SessionFS - A session based VFS wrapper: src/kmodule/device_sessionfs.c File Reference
device_sessionfs.c File Reference
Implementation of the virtual character device that will handle sessions, component of the Character Device submodule.
#include "device_sessionfs.h"
#include "device_sessionfs_mod.h"
#include "session_manager.h"
#include "session_info.h"
#include <linux/fs.h>
#include <linux/slab.h>
#include <linux/uaccess.h>
#include <uapi/linux/limits.h>
#include <linux/device.h>
#include <linux/module.h>
#include <uapi/asm-generic/errno.h>
#include <linux/pid.h>
#include <linux/sched.h>
#include <linux/spinlock.h>
#include <linux/sched/signal.h>
#include <linux/namei.h>
#include <linux/path.h>
#include <linux/dcache.h>
Macros
#define DEFAULT_SESS_PATH "/mnt"
The default session path when the device is initialized.
#define DEVICE_DISABLED 1
Indicates that the device has been disabled and is being removed.
#define PATH_OK 1
Indicates that the given path is contained in sess_path
Functions
long int device_ioctl (struct file *file, unsigned int num, unsigned long param)
Handles the ioctls calls issued to the SessionFS_dev device.
static ssize_t device_read (struct file *file, char *buffer, size_t buflen, loff_t *offset)
Get the path in which sessions are enabled.
static ssize_t device_write (struct file *file, const char *buffer, size_t buflen, loff_t *offset)
Writes a new path in which sessions must be enabled.
int init_device (void)
Device initialization and registration.
int path_check (const char *path)
Check if the given path is a subpath of sess_path
void release_device (void)
Releases the device and frees the used memory.
static char * sessionfs_devnode (struct device *dev, umode_t *mode)
Allows every user to read and write the device file of our virtual device.
Variables
struct device * dev =NULL
Device object.
struct class * dev_class =NULL
Device class.
rwlock_t dev_lock
Lock that protects the session path from concurrent accesses.
struct file_operations * dev_ops =NULL
File operations allowed on our device.
atomic_t device_status
Indicates that the device must not be used since is being removed.
int path_len =0
Length of the of the path string.
atomic_t refcount
Refcount of the processes that are using the device.
char * sess_path =NULL
The path to the directory in which session sematic is enabled.
Detailed Description
Implementation of the virtual character device that will handle sessions, component of the Character Device submodule.
This file contains the implementation of the device operations that will handle the session semantics and the interaction with the path where sessions are enabled.
Function Documentation
device_ioctl()
long int device_ioctl (struct file * file, unsigned int num, unsigned long param)
Handles the ioctls calls issued to the SessionFS_dev device.
Parameters
[in] file The special file that represents our char device.
[in] num The ioctl sequence number, used to identify the operation to be executed, its possible values are IOCTL_SEQ_OPEN, IOCTL_SEQ_CLOSE and IOCTL_SEQ_SHUTDOWN.
[in,out] param The ioctl param, which is a sess_params struct, that contains the information on the session that must be opened/closed and will be updated with the information on the result of the operation.
Returns
0 on success or an error code. (-ENODEV if the device is disabled, -EINVAL if path_check() fails or parameters are invalid, -EAGAIN if the copy_to_user fails and -EPIPE plus a SIGPIPE signal if the original file can't be found.)
This function checks device_status, increments refcount, then copies the sess_params struct and its orig_pathname in kernel space. Its behaviour differs in base of the ioctl sequence number specified:
IOCTL_SEQ_OPEN: Tries to create a session by invoking create_session(). If the session and the incarnation are created successfully the file descriptor of the incarnation is copied into sess_params filedes member. If the incarnation gets corrupted during creation, the filedes member of sess_params is updated as in the successful case, but the corresponding error code is returned, so that the library can close and remove the corrupted incarnation file.
IOCTL_SEQ_CLOSE: closes an open session using close_session() and the incarnation file must be closed and removed by the library. If the original file does not exist anymore it sends SIGPIPE to the user process.
IOCTL_SEQ_SHUTDOWN: disables the device, setting device_status to DEVICE_DISABLED, to avoid race conditions. Then calls clean_manager() to check if there are active sessions. If there are no active sessions and the refcount is 1 (we are the only process using the device) then the module is unlocked, using module_put(). Otherwise the device is re-enabled, setting device_status to !DEVICE_DISABLED and the ioctl fails with -EAGAIN.
To allow the unload of the module we need to have no active sessions, no processes that are using the device and no processes that are using the device kobject.
References clean_manager(), close_session(), create_session(), dev, DEVICE_DISABLED, device_status, IOCTL_SEQ_CLOSE, IOCTL_SEQ_OPEN, IOCTL_SEQ_SHUTDOWN, O_SESS, path_check(), PATH_OK, refcount, and sess_path.
Referenced by init_device().
device_read()
static ssize_t device_read (struct file * file, char * buffer, size_t buflen, loff_t * offset) static
Get the path in which sessions are enabled.
Parameters
[out] buffer The buffer in which the path is copied.
[in] buflen The lenght of the supplied buffer.
file unused, but necessary to fit the function into struct file_operations.
offset unused, but necessary to fit the function into struct file_operations.
Returns
The number of bytes written in buffer, or an error code (-EINVAL if one of the supplied parameters is invalid, -EAGAIN if the copy_to_user() failed, -ENODEV if the device is disabled).
This function will copy the sess_path content in the supplied buffer. The first operations be executed are the check for the device status on device_status, the incrementation of the refcount. Then dev_lock is grabbed for reading; after the operation is completed dev_lock is released and the refcount is decremented.
References dev_lock, DEVICE_DISABLED, device_status, path_len, refcount, and sess_path.
Referenced by init_device().
device_write()
static ssize_t device_write (struct file * file, const char * buffer, size_t buflen, loff_t * offset) static
Writes a new path in which sessions must be enabled.
Parameters
[in] buffer The new path in which session are enabled.
[in] buflen The length of the provided buffer.
file unused, but necessary to fit the function into struct file_operations.
offset unused, but necessary to fit the function into struct file_operations.
Returns
The number of bytes written in buffer, or an error code (-EINVAL if one of the supplied parameters are invalid, -EAGAIN if the copy_from_user failed, -ENODEV if the device is disabled).
This function will reset and overwrite sess_path, without affecting existing sessions, if the supplied path is absolute. To do so we check device_status and we increment refcount. Then we check that the supplied path starts with '/', grab dev_lock for write operations, we zero-fill sess_path, copy the new string and add a terminator, just in case. Finally we release dev_lock and decrement refcount.
References dev_lock, DEVICE_DISABLED, device_status, path_len, refcount, and sess_path.
Referenced by init_device().
init_device()
int init_device (void)
Device initialization and registration.
Initializes and registers the device by setting sess_path, path_len variables: dev_ops will contain the operations allowed on the device, which are device_ioctl(), device_read() and device_write(), and the sessionfs_devnode() callback to set the inode permissions. The Session Manager submodule is also initialized using init_manager() and the same happens for the Session Information submodule, using init_info(), after the device is registered. Finally we lock the module with try_module_get() to prevent it being unmounted while is in use.
References CLASS_NAME, DEFAULT_SESS_PATH, dev, dev_class, dev_lock, dev_ops, DEVICE_DISABLED, device_ioctl(), DEVICE_NAME, device_read(), device_status, device_write(), init_info(), init_manager(), MAJOR_NUM, path_len, refcount, sess_path, and sessionfs_devnode().
Referenced by sessionFS_load().
path_check()
int path_check (const char * path)
Check if the given path is a subpath of sess_path
Gets the dentry from the given path and from sess_path and checks if the second dentry is an ancestor of the first dentry.
Parameters
[in] path Path to be checked
Returns
PATH_OK if the given path is a subpath of sess_path and !PATH_OK otherwise; an error code is returned on error.
If the dentry corresponding to the given path cannot be found, the function will check if sess_path is a substring of the given path.
References dev_lock, PATH_OK, and sess_path.
Referenced by device_ioctl().
release_device()
void release_device (void)
Releases the device and frees the used memory.
Unregisters the device, cleans the Session Manager just to be sure to avoid memory leaks, releases the Session Information and frees the used memory (dev_ops and sess_path).
References clean_manager(), dev_class, dev_ops, DEVICE_DISABLED, DEVICE_NAME, device_status, MAJOR_NUM, release_info(), and sess_path.
Referenced by sessionFS_unload().
sessionfs_devnode()
static char* sessionfs_devnode (struct device * dev, umode_t * mode) static
Allows every user to read and write the device file of our virtual device.
Parameters
[in] dev Our device struct.
[out] mode The permissions we set to our device.
With this callback that is added to dev_ops we set the permissions of the inode in /dev that represents our device, allowing every user to read and write in it.
References dev, and MAJOR_NUM.
Referenced by init_device().
Variable Documentation
sess_path
char* sess_path =NULL
The path to the directory in which session sematic is enabled.
Keeps the path to the directory in which session sematic is enabled (located in ::device_sessionfs.c).
Referenced by close(), device_ioctl(), device_read(), device_write(), init_device(), open(), path_check(), and release_device().