SessionFS - A session based VFS wrapper: src/kmodule/device_sessionfs_mod.h File Reference
device_sessionfs_mod.h File Reference
Device properties needed to the kernel module, component of the Character Device submodule.
Functions
int init_device (void)
Device initialization and registration.
void release_device (void)
Releases the device and frees the used memory.
Variables
char * sess_path
Keeps the path to the directory in which session sematic is enabled (located in ::device_sessionfs.c).
Detailed Description
Device properties needed to the kernel module, component of the Character Device submodule.
This file contains the properties of the device that are needed to the kernel module, such as the prototypes of the device init and cleanup functions and the buffer that will contain the path in which sessions are enabled.
Function Documentation
init_device()
int init_device (void)
Device initialization and registration.
Returns
0 on success -1 on error.
Initializes and registers the device by setting sess_path, path_len variables: dev_ops will contain the operations allowed on the device, which are device_ioctl(), device_read() and device_write(), and the sessionfs_devnode() callback to set the inode permissions. The Session Manager submodule is also initialized using init_manager() and the same happens for the Session Information submodule, using init_info(), after the device is registered. Finally we lock the module with try_module_get() to prevent it being unmounted while is in use.
References CLASS_NAME, DEFAULT_SESS_PATH, dev, dev_class, dev_lock, dev_ops, DEVICE_DISABLED, device_ioctl(), DEVICE_NAME, device_read(), device_status, device_write(), init_info(), init_manager(), MAJOR_NUM, path_len, refcount, sess_path, and sessionfs_devnode().
Referenced by sessionFS_load().
release_device()
void release_device (void)
Releases the device and frees the used memory.
Unregisters the device, cleans the Session Manager just to be sure to avoid memory leaks, releases the Session Information and frees the used memory (dev_ops and sess_path).
References clean_manager(), dev_class, dev_ops, DEVICE_DISABLED, DEVICE_NAME, device_status, MAJOR_NUM, release_info(), and sess_path.
Referenced by sessionFS_unload().
Variable Documentation
sess_path
char* sess_path
Keeps the path to the directory in which session sematic is enabled (located in ::device_sessionfs.c).
Keeps the path to the directory in which session sematic is enabled (located in ::device_sessionfs.c).
Referenced by close(), device_ioctl(), device_read(), device_write(), init_device(), open(), path_check(), and release_device().