SessionFS - A session based VFS wrapper: src/shared_lib/libsessionfs.c File Reference
libsessionfs.c File Reference
Implementation of the userspace shared library.
#include <dlfcn.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <stdarg.h>
#include "libsessionfs.h"
Macros
#define _GNU_SOURCE
Enables RTLD_NEXT macro.
#define DEV_PATH "/dev/SessionFS_dev"
The path of our device file.
Typedefs
typedef int(* orig_close_type) (int filedes)
A typedef to aliases the function pointer to the libc close.
typedef int(* orig_open_type) (const char *pathname, int flags)
A typedef that aliases the function pointer to the libc open.
Functions
static __attribute__ ((constructor))
A program constructor which saves the original value for the open and close symbols.
int close (int fd)
Wraps the close determining if it must call the libc close or the SessionFS module.
int device_shutdown (void)
Asks to shut down the SessionFS_dev device.
int get_sess_path (char *buf, int bufsize)
Gets the current session path.
int open (const char *pathname, int flags,...)
Wraps the open determining if it must call the libc open or the SessionFS module.
int write_sess_path (char *path)
Changes the current session path.
Variables
orig_close_type orig_close
Global variable that holds the function pointer for libc close
orig_open_type orig_open
Global variable that holds the function pointer for libc open
Detailed Description
Implementation of the userspace shared library.
Used to provide a trasparent interface to the userspace application, that can use the libc open and close functions, along with the O_SESS flag to work with sessions. To change session path instead, it can use the get_sess_path() and write_sess_path() utility functions, to avoid the direct communication with the SessionFS_dev device.
Function Documentation
__attribute__()
static __attribute__ ((constructor)) static
A program constructor which saves the original value for the open and close symbols.
Returns
0 on success or -1 on error, setting errno.
We save the original open and close since the library needs to understand when it's necessary to use the char device and when the libc implementation must be used. To do so we save them we use the dlsym function and we define two new types to avoid using a function pointer directly: orig_open_type and orig_close_type, these are simple typedefs that wrap the function poitner for libc open and close.
References orig_close, and orig_open.
close()
int close (int fd)
Wraps the close determining if it must call the libc close or the SessionFS module.
Parameters
[in] fd file descriptor to deallocate, same as libc open's fildes.
Returns
0 on success, -1 on error, setting errno to indicate the error value.
To determine if libc close must be used, the file pathname is read from /proc/self/fd, then readlink is used to resolve the pathname and make it absolute, finally, if this pathname contains the _incarnation_[pid]_ substring then it must be closed by issuing an ioctl with number IOCTL_SEQ_CLOSE to the SessionFS_dev device. Otherwise the libc close is called. A sess_params struct is used to pass parameters to the char device when necessary. After the device completes its operations libc close is called to remove the file descriptor and remove is called to delete the incarnation file from the disk. If the return value from the ioctl is -ENODEV the the device was temporarly disabled and the operation must be retried.
References dev, DEV_PATH, IOCTL_SEQ_CLOSE, orig_close, orig_open, and sess_path.
Referenced by fork_test(), func_test(), open(), and sess_change_test().
device_shutdown()
int device_shutdown (void)
Asks to shut down the SessionFS_dev device.
To power down the device we only need to execute an ioctl with number IOCTL_SEQ_SHUTDOWN and the devce will proceed accordingly.
References dev, DEV_PATH, IOCTL_SEQ_SHUTDOWN, orig_close, and orig_open.
Referenced by main().
get_sess_path()
int get_sess_path (char * buf, int bufsize)
Gets the current session path.
This function is a simple utility function that reads from the SessionFS_dev device, located at DEV_PATH, the current session path and places it in the buffer provided by the caller.
References dev, DEV_PATH, orig_close, and orig_open.
Referenced by change_sess_path(), and open().
open()
int open (const char * pathname, int flags, ...)
Wraps the open determining if it must call the libc open or the SessionFS module.
Parameters
[in] pathname The pathname of the file to be opened, same usage an type of the libc open's pathname.
[in] flags Flags to determine the file status flag and the access modes, same as the libc open's oflag, however a possible flag is the O_SESS flag which enables the session semantic.
[in] mode An optional parameter, which defines the permissions to set if a file must be created, (when O_CREAT is specified).
Returns
It will return a file descriptor if the operation is successful, or -1, setting errno.
This function will check for the presence of the O_SESS flag and if the path of the file to be opened has as a substring the session path.
If the checks are successful, the function will perform an ioctl call to the SessionFS kernel module, via the SessionFS_dev device, to open a new session for the given pathname. Otherwise, the function will call the libc implementation of the open systemcall.
To check that the given path has sess_path as a substring, realpath() is used, to convert the pathname to absolute. If realpath() fails with ENOENT, the path provided might be the relative path to a file that must be created, so the path of the current diretory is used as the file path.
To perform the ioctl the IOCTL_SEQ_OPEN number is used and struct sess_params is filled and passed as an argument, to provide all the necessary informations to the device.
If the opened session is not valid, the function will call close() to remove the invalid session in a clean way and the function will fail with EAGAIN.
When creating a new file we need to call creat since we have the symbol only for the open with two parametrs.
References close(), dev, DEV_PATH, get_sess_path(), IOCTL_SEQ_OPEN, O_SESS, orig_close, orig_open, sess_path, and VALID_SESS.
Referenced by fork_test(), func_test(), and sess_change_test().
write_sess_path()
int write_sess_path (char * path)
Changes the current session path.
This function is a simple utility function that writes on the SessionFS_dev device, located at DEV_PATH, the content of the buffer provided by the user; before doing so however, it uses the realpath() function to make sure that the path provided to char device is an absolute path.
References dev, DEV_PATH, orig_close, and orig_open.
Referenced by change_sess_path().