SessionFS - A session based VFS wrapper: src/shared_lib/libsessionfs.h File Reference
libsessionfs.h File Reference
Shared library header.
#include <errno.h>
#include <limits.h>
#include "../kmodule/device_sessionfs.h"
Functions
int device_shutdown (void)
Asks to shut down the SessionFS_dev device.
int get_sess_path (char *buf, int bufsize)
Gets the current session path.
int write_sess_path (char *path)
Changes the current session path.
Detailed Description
Shared library header.
Header file for the shared library that wraps the open and close functions. Contains only get_sess_path(), write_sess_path() and device_shutdown() since the open() and close() functions are used to wrap the libc syscalls and do not need to be exported.
Function Documentation
device_shutdown()
int device_shutdown (void)
Asks to shut down the SessionFS_dev device.
Returns
0 on success, -EAGAIN if the device is in use and cannot be removed.
To power down the device we only need to execute an ioctl with number IOCTL_SEQ_SHUTDOWN and the devce will proceed accordingly.
References dev, DEV_PATH, IOCTL_SEQ_SHUTDOWN, orig_close, and orig_open.
Referenced by main().
get_sess_path()
int get_sess_path (char * buf, int bufsize)
Gets the current session path.
Parameters
[out] buf The buffer which will contain the output, must be provided.
[in] bufsize The length of the provided buffer.
Returns
The number of bytes read or an error code.
This function is a simple utility function that reads from the SessionFS_dev device, located at DEV_PATH, the current session path and places it in the buffer provided by the caller.
References dev, DEV_PATH, orig_close, and orig_open.
Referenced by change_sess_path(), and open().
write_sess_path()
int write_sess_path (char * path)
Changes the current session path.
Parameters
[in] buf The buffer which will contain the new path.
Returns
The number of bytes written or an error code.
This function is a simple utility function that writes on the SessionFS_dev device, located at DEV_PATH, the content of the buffer provided by the user; before doing so however, it uses the realpath() function to make sure that the path provided to char device is an absolute path.
References dev, DEV_PATH, orig_close, and orig_open.
Referenced by change_sess_path().