SessionFS - A session based VFS wrapper: src/kmodule/session_info.c File Reference
session_info.c File Reference
Implementation of the Session Information submodule.
#include "session_info.h"
#include <linux/kernel.h>
#include <linux/pid.h>
#include <linux/sched.h>
#include <linux/slab.h>
Macros
#define KERN_OBJ_PERM 0444
Kernel objects attributes are read only, since we only read information on sessions.
Functions
ssize_t active_incarnations_num_show (struct kobject *obj, struct kobj_attribute *attr, char *buf)
The function used to read the SysFS active_incarnations_num attribute file.
ssize_t active_sessions_num_show (struct kobject *obj, struct kobj_attribute *attr, char *buf)
The function used to read the SysFS active_sessions_num attribute file.
int add_incarnation_info (struct sess_info *parent_session, struct kobj_attribute *incarnation, pid_t pid, int fdes)
Adds a new kobject attribute representing an incarnation.
int add_session_info (const char *name, struct sess_info *session)
Adds a new kobject representing an original file, under the SessionFS kobject.
int init_info (struct kobject *device_kobj)
Initializes the SessionFS kobject with general information about the running sessions.
ssize_t proc_name_show (struct kobject *obj, struct kobj_attribute *attr, char *buf)
The function used to read the SysFS incarnations attribute files.
void release_info (void)
Removes the SessionFS information from the device provided in init_info().
void remove_incarnation_info (struct sess_info *parent_session, struct kobj_attribute *incarnation)
Removes the kobject attribute incarnation from a kobject.
void remove_session_info (struct sess_info *session)
Removes a session kobject.
Variables
struct kobject * dev_kobj
The device kobject provided during init_info().
struct kobj_attribute kattr = __ATTR_RO(active_sessions_num)
The kernel attribute that will contain the number of open sessions.
atomic_t sessions_num
The number of opened sessions.
Detailed Description
Implementation of the Session Information submodule.
Function Documentation
active_incarnations_num_show()
ssize_t active_incarnations_num_show (struct kobject * obj, struct kobj_attribute * attr, char * buf)
The function used to read the SysFS active_incarnations_num attribute file.
Parameters
[in] obj The kobject that has the attribute being read.
[in] attr The attribute of the kobject that is being read.
[out] buf The buffer (which is PAGE_SIZE bytes long) that contains the file contents.
Returns
The number of bytes read (in [0,PAGE_SIZE]). The file content returned is the number of active incarnations for the current original file.
Referenced by add_session_info().
active_sessions_num_show()
ssize_t active_sessions_num_show (struct kobject * obj, struct kobj_attribute * attr, char * buf)
The function used to read the SysFS active_sessions_num attribute file.
Parameters
[in] obj The kobject that has the attribute being read.
[in] attr The attribute of the kobject that is being read.
[out] buf The buffer (which is PAGE_SIZE bytes long) that contains the file contents.
Returns
The number of bytes read (in [0,PAGE_SIZE]). The file content is the number of active sessions.
References sessions_num.
add_incarnation_info()
int add_incarnation_info (struct sess_info * parent_session, struct kobj_attribute * incarnation, pid_t pid, int fdes)
Adds a new kobject attribute representing an incarnation.
By adding a new incarnation we increment active_sessions_num and active_incarnations_num for the given session, represented by its sess_info member, also, a kobject attribute is added to the given session that has the process pid as filename and contains the process name. Finally the reference counter of the given session is also incremented.
The format of the file found on SysFS [pid]_[file descriptor], to allow the same process to have the process open the same file multiple times.
References KERN_OBJ_PERM, proc_name_show(), and sessions_num.
Referenced by create_incarnation().
add_session_info()
int add_session_info (const char * name, struct sess_info * session)
Adds a new kobject representing an original file, under the SessionFS kobject.
We add a new folder in sysfs which is represented by the given kobject. The session kobject, represented by the sess_info member the session object will be created as a child of dev_kobj, and the dev_kobj reference counter will be incremented.
We also format the filename substituting '/' with '-'.
Finally, initialize the number of incarnations as a kobj_attribute.
References active_incarnations_num_show(), dev_kobj, and KERN_OBJ_PERM.
Referenced by init_session().
init_info()
int init_info (struct kobject * device_kobj)
Initializes the SessionFS kobject with general information about the running sessions.
We add an attribute called active_sessions_num to the SessionFS device kernel object, which is only readable and its content is the number of active sessions.
References dev_kobj, kattr, and sessions_num.
Referenced by init_device().
proc_name_show()
ssize_t proc_name_show (struct kobject * obj, struct kobj_attribute * attr, char * buf)
The function used to read the SysFS incarnations attribute files.
Parameters
[in] obj The kobject that has the attribute being read.
[in] attr The attribute of the kobject that is being read.
[out] buf The buffer (which is PAGE_SIZE bytes long) that contains the file contents.
Returns
The number of bytes read (in [0,PAGE_SIZE]). The file content is the process name that corresponds to the pid used as filename.
Referenced by add_incarnation_info().
release_info()
void release_info (void)
Removes the SessionFS information from the device provided in init_info().
We remove the 'active_sessions_num' attribute from the device
References dev_kobj, and kattr.
Referenced by release_device().
remove_incarnation_info()
void remove_incarnation_info (struct sess_info * parent_session, struct kobj_attribute * incarnation)
Removes the kobject attribute incarnation from a kobject.
By removing an incarnation we decrement active_sessions_num and active_incarnations_num for the given session, represented by its sess_info member. Also, the kobject attribute that has the process pid as filename and contains the process name is removed from the given session. Finally the reference counter of the given session is also decremented.
References sessions_num.
Referenced by clean_manager(), and delete_incarnation().
remove_session_info()
void remove_session_info (struct sess_info * session)
Removes a session kobject.
Removes the entry corresponding to the given session, represented by its sess_info member, in the device SysFS folder. To do so we also remove the active_incarnations_num file of the given session and we decrement the reference counter of the device session kernel object.
References dev_kobj.
Referenced by clean_manager(), and close_session().