SessionFS - A session based VFS wrapper: src/kmodule/session_manager.h File Reference
session_manager.h File Reference
APIs used to interact with the session manger, component of the Session Manager submodule.
#include <linux/types.h>
#include "session_types.h"
Functions
int clean_manager (void)
Releases all the incarnations that are associated with a dead/zombie pid.
int close_session (const char *pathname, int fdes, pid_t pid)
Closes a session.
struct incarnation * create_session (const char *pathname, int flags, pid_t pid, mode_t mode)
Create a new session for the specified file.
int init_manager (void)
Initialization of the session manager data structures.
Detailed Description
APIs used to interact with the session manger, component of the Session Manager submodule.
This file contains the APIs of the session manager, which are used to initialize and release the manager and to add and remove sessions.
Function Documentation
clean_manager()
int clean_manager (void)
Releases all the incarnations that are associated with a dead/zombie pid.
Returns
the number of sessions associated with an active pid.
This method will walk through the sessions list and each incarnation list, deleting all the incarnation(s) and session(s) in which the process that has requested it is not active anymore, leaving the original files untouched. If there is an incarnation that is still in use by an active process it will be preserved.
To check if an incarnation is still active we get the struct pid from the pid number included in the incarnation; if we receive it, the process is at most in a zombie state.
When walking the sessions list we increment the refcount of the session in use to avoid having it removed while we are using it. We remove all the elements in the incarnations lockless list and we add back the objects, closing the others without modifing the original file and updating SysFS with remove_incarnation_info(), without deallcoating the dead incarnation(s). If a session has no active incarnations it will be flagged as invalid and removed during a second walk, where, with delete_incarnation(), we remove all the invalid session(s) and deallocate al the associated incarnation(s).
NOTE: For dead incarnations that have not been closed we leave the files in the folder, since can't remove them from kernel space. Userspace will need to manually remove incarnations file for invalid processes.
We consider as invalid a session which is associated to a dead process.
References delete_session(), delete_session_rcu(), MANAGER_EMPTY, remove_incarnation_info(), remove_session_info(), sessions, sessions_lock, and VALID_NODE.
Referenced by device_ioctl(), and release_device().
close_session()
int close_session (const char * pathname, int fdes, pid_t pid)
Closes a session.
Parameters
[in] pathname the pathname for the session containing the incarnation that is being closed.
[in] fdes The file descriptor of a session incarnation.
[in] pid The owner process pid.
Returns
0 on success or an error code.
This function will close one session, by finding the corresponding incarnation, using search_session(), copying the incarnation file over the original file (atomically in respect to other session operations on the same original file, and only if the session is valid), and deleting the incarnation, using delete_incarnation(). If after the incarnation deletion the session has no other incarnation(s) the it will also schedule the session to be removed.
If we cannot locate the parent session of an incarnation -EBADF is returned.
To remove a session object we need to check several conditions:
The session must be not in use by other threads (refcount==1)
The session kernel object refcount, in the info member, must be 1
The session must be still valid and not already marked for deletion
If the current session must be removed, we flag it as invalid, to avoid having new incarnations created in here before deallocating it and making sure that it will be eventually deallocated.
We also remove its information on SysFS using remove_session_info().
Then, we can remove the current session object from the rcu list, using the sessions_lock spinlock to avoid concurrent operations.
Finally, we try to deallocate the session if is invalid, using delete_session().
References delete_incarnation(), delete_session(), delete_session_rcu(), OVERWRITE_ORIG, remove_session_info(), search_session(), sessions_lock, and VALID_NODE.
Referenced by device_ioctl().
create_session()
struct incarnation* create_session (const char * pathname, int flags, pid_t pid, mode_t mode)
Create a new session for the specified file.
Parameters
[in] pathname The pathname of the file in which the session will be created.
[in] flags The flags that specify the permissions on the file.
[in] pid The pid of the process that wants to create the session.
[in] mode The permissions to apply to newly created files.
Returns
a pointer to an incarnation object, containing all the info on the current incarnation or an error code.
To create a new session we check if the original file was already opened with session semantic, by searching for an existing session with the same pathname using search_session(). If the found session is invalid or a matching session object is not found a new session object will be created, using init_session(). Then we create a new incarnation of the original file with create_incarnation().
When the incarnation has been created the refcount of the parent session is decremented.
-EAGAIN is returned if the created session is invalid.
References create_incarnation(), delete_session(), init_session(), NO_FD, NO_PID, search_session(), and VALID_NODE.
Referenced by device_ioctl().
init_manager()
int init_manager (void)
Initialization of the session manager data structures.
Returns
0 on success or an error code.
Initializes the sessions global variable as an empty list. Avoids the RCU initialization since we can't receive requests yet, so no one will use this list for now. Then initializes the sessions_lock spinlock.
References sessions, and sessions_lock.
Referenced by init_device().