SessionFS - A session based VFS wrapper: src/kmodule/session_manager.c File Reference
session_manager.c File Reference
Implementation of the Session Manager submodule.
#include <linux/types.h>
#include <uapi/linux/limits.h>
#include <linux/spinlock.h>
#include <linux/llist.h>
#include <linux/list.h>
#include <linux/rculist.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/slab.h>
#include <linux/err.h>
#include <uapi/asm-generic/errno.h>
#include <linux/timekeeping.h>
#include <uapi/asm-generic/fcntl.h>
#include <linux/fsnotify.h>
#include <linux/pid.h>
#include "session_manager.h"
#include "session_info.h"
Macros
#define DATA_DIM 512
The portion of the file which is copied at each read/write iteration.
#define DEFAULT_PERM 0644
Permissions to be given to the newly created files.
#define MANAGER_EMPTY 0
Used to determine is the session manager contains active sessions.
#define NO_FD 0
Used to toggle the necessity of a file descriptor in open_file() and to determine the type of search in search_session().
#define NO_PID 0
Used to determine the type of search in search_session().
#define OVERWRITE_ORIG 0
Used to determine if the content of the incarnation must overwrite the original file on close.
#define VALID_NODE 0
Used to determine if a session node is valid.
Functions
int clean_manager (void)
Releases all the incarnations that are associated with a dead/zombie pid.
int close_session (const char *pathname, int fdes, pid_t pid)
Closes a session.
int copy_file (struct file *src, struct file *dst)
Copy the contents of a file into another.
struct incarnation * create_incarnation (struct session *session, int flags, pid_t pid, mode_t mode)
Creates an incarnation and add it to an existing session.
struct incarnation * create_session (const char *pathname, int flags, pid_t pid, mode_t mode)
Create a new session for the specified file.
int delete_incarnation (struct session *session, int filedes, pid_t pid, int overwrite)
Removes the given incarnation.
void delete_session (struct session *session)
Deallocates the given session object.
void delete_session_rcu (struct rcu_head *head)
Deallocates a session_rcu element.
int init_manager (void)
Initialization of the session manager data structures.
struct session * init_session (const char *pathname, int flags, mode_t mode)
Initializes the session information for the given pathname.
int open_file (const char *pathname, int flags, mode_t mode, int fd_needed, struct file **file)
Opens a file from kernel space.
struct session * search_session (const char *pathname, int filedes, pid_t pid)
Searches for a session with a given pathname, or with an incarnation with matching pid and file descriptor.
Variables
struct list_head sessions
List of the active session(s).
spinlock_t sessions_lock
Spinlock used to update the list of the active session(s)
Detailed Description
Implementation of the Session Manager submodule.
This file contains the implementation of the session manager, which will handle the creation and deletion of a session, keeping track of the opened sessions for each file.
Function Documentation
clean_manager()
int clean_manager (void)
Releases all the incarnations that are associated with a dead/zombie pid.
This method will walk through the sessions list and each incarnation list, deleting all the incarnation(s) and session(s) in which the process that has requested it is not active anymore, leaving the original files untouched. If there is an incarnation that is still in use by an active process it will be preserved.
To check if an incarnation is still active we get the struct pid from the pid number included in the incarnation; if we receive it, the process is at most in a zombie state.
When walking the sessions list we increment the refcount of the session in use to avoid having it removed while we are using it. We remove all the elements in the incarnations lockless list and we add back the objects, closing the others without modifing the original file and updating SysFS with remove_incarnation_info(), without deallcoating the dead incarnation(s). If a session has no active incarnations it will be flagged as invalid and removed during a second walk, where, with delete_incarnation(), we remove all the invalid session(s) and deallocate al the associated incarnation(s).
NOTE: For dead incarnations that have not been closed we leave the files in the folder, since can't remove them from kernel space. Userspace will need to manually remove incarnations file for invalid processes.
We consider as invalid a session which is associated to a dead process.
References delete_session(), delete_session_rcu(), MANAGER_EMPTY, remove_incarnation_info(), remove_session_info(), sessions, sessions_lock, and VALID_NODE.
Referenced by device_ioctl(), and release_device().
close_session()
int close_session (const char * pathname, int fdes, pid_t pid)
Closes a session.
This function will close one session, by finding the corresponding incarnation, using search_session(), copying the incarnation file over the original file (atomically in respect to other session operations on the same original file, and only if the session is valid), and deleting the incarnation, using delete_incarnation(). If after the incarnation deletion the session has no other incarnation(s) the it will also schedule the session to be removed.
If we cannot locate the parent session of an incarnation -EBADF is returned.
To remove a session object we need to check several conditions:
The session must be not in use by other threads (refcount==1)
The session kernel object refcount, in the info member, must be 1
The session must be still valid and not already marked for deletion
If the current session must be removed, we flag it as invalid, to avoid having new incarnations created in here before deallocating it and making sure that it will be eventually deallocated.
We also remove its information on SysFS using remove_session_info().
Then, we can remove the current session object from the rcu list, using the sessions_lock spinlock to avoid concurrent operations.
Finally, we try to deallocate the session if is invalid, using delete_session().
References delete_incarnation(), delete_session(), delete_session_rcu(), OVERWRITE_ORIG, remove_session_info(), search_session(), sessions_lock, and VALID_NODE.
Referenced by device_ioctl().
copy_file()
int copy_file (struct file * src, struct file * dst)
Copy the contents of a file into another.
Parameters
[in] src The source file.
[in] dst The destination file.
Returns
0 on success, an error code on failure.
Reads DATA_DIM bytes from src and writes them on dst, starting in both files from the beginning and stopping when src is has been completely read.
References DATA_DIM.
Referenced by create_incarnation(), and delete_incarnation().
create_incarnation()
struct incarnation* create_incarnation (struct session * session, int flags, pid_t pid, mode_t mode)
Creates an incarnation and add it to an existing session.
Parameters
[in] session The session object that represents the file in which we want to create a new incarnation.
[in] flags The flags the regulates how the file must be opened.
[in] pid The pid of the process that wants the create a new incarnation.
[in] mode The permissions to apply to newly created files.
Returns
The file descriptor of the new incarnation or an error code (-EAGAIN if the parent session is invalid).
Creates an incarnation by updating the information on SysFS using add_incarnation_info() and opening a new file, using open_file(), copying the contents of the original file in the new file, using copy_file().Then creates an incarnation object, filling it with info and adding it to the incarnations list of the parent session.
The original flags will be modified by adding the O_CREAT flag, since the incarnation file must always be created.
If the created incarnation is invalid the error code that has invalidated the session can be found in the incarnation status parameter.
If we have an invalid parent session we return -EAGAIN.
The incarnation file name has the following format: [original filename]_incarnation_[pid]_[timestamp] to make the incarnation file unique. If the original pathname is too long we use the following format /var/tmp/[pid]_[timestamp]. The timestamp is obtained by calling ktime_get_real().
We need to grab the parent session lock in read mode from when we copy the original file over the incarnation file; since we do not need to protect the lockless list when adding elements, but the session incarnations must be created atomically in respect to close operations on the same original file The lock is released when the incarnation has been added to the list.
References add_incarnation_info(), copy_file(), NO_FD, open_file(), and VALID_NODE.
Referenced by create_session().
create_session()
struct incarnation* create_session (const char * pathname, int flags, pid_t pid, mode_t mode)
Create a new session for the specified file.
To create a new session we check if the original file was already opened with session semantic, by searching for an existing session with the same pathname using search_session(). If the found session is invalid or a matching session object is not found a new session object will be created, using init_session(). Then we create a new incarnation of the original file with create_incarnation().
When the incarnation has been created the refcount of the parent session is decremented.
-EAGAIN is returned if the created session is invalid.
References create_incarnation(), delete_session(), init_session(), NO_FD, NO_PID, search_session(), and VALID_NODE.
Referenced by device_ioctl().
delete_incarnation()
int delete_incarnation (struct session * session, int filedes, pid_t pid, int overwrite)
Removes the given incarnation.
Parameters
[in] session The session containing the incarnation to be removed.
[in] filedes The file descriptor that identifies the incarnation
[in] pid The pid of the owner of the incarnation.
[in] overwrite If set to OVERWRITE_ORIG it will overwrite the original file with the content of the incarnation which is going to be removed, otherwise the current incarnation is simply removed.
Returns
0 or an error code (-ENOENT if the incarnation can't be found).
Searches the incarnations list of the given session for the current incarnation, copies the contents of the incarnation over the original file (if overwrite is set to OVERWRITE_ORIG) and marks it as invalid. The userspace library needs to close and remove the file.
When the incarnation is removed, SysFS is updated with remove_incarnation_info(). There could be processes still referencing the incarnation associated SysFS files after their removal, so the incarnation will remain in the lockless list and will be deallocated when the session will be deleted.
The incarnation to be closed will be marked as invalid, by setting its status member to -ENOENT
References copy_file(), OVERWRITE_ORIG, remove_incarnation_info(), and VALID_NODE.
Referenced by close_session().
delete_session()
void delete_session (struct session * session)
Deallocates the given session object.
Parameters
[in] session The session object to deallocate.
This function is used to free the memory used by the session when nobody is accessing it, this is checked using the session refcount and the session kernel object refcount, in the info member.
The method will attempt to deallocate the session object, with all its incarnations, if the session refcount is 0 and the associated kernel object refcount is 1 (only the current process is using it). Otherwise the method will do nothing.
Referenced by clean_manager(), close_session(), create_session(), and init_session().
delete_session_rcu()
void delete_session_rcu (struct rcu_head * head)
Deallocates a session_rcu element.
Parameters
[in] head The rcu_head struct contained inside the session_rcu to deallcoate.
Used to deallocate the session_rcu element after it has been removed from the sessions list.
DO NOT directly call this function, instead you should let this function be called by call_rcu() when nobody is accessing anymore this element.
Referenced by clean_manager(), close_session(), and init_session().
init_manager()
int init_manager (void)
Initialization of the session manager data structures.
Initializes the sessions global variable as an empty list. Avoids the RCU initialization since we can't receive requests yet, so no one will use this list for now. Then initializes the sessions_lock spinlock.
References sessions, and sessions_lock.
Referenced by init_device().
init_session()
struct session* init_session (const char * pathname, int flags, mode_t mode)
Initializes the session information for the given pathname.
Parameters
[in] pathname The path of the original file.
[in] flags The flags that regulate the access to the original file.
[in] mode The permissions to apply to newly created files.
To create a new session object we open the matching file using open_file(), then we get the spinlock sessions_lock to avoid race coditions and a search is issued, using search_session(), to see if there is already a matching session with the same pathname to be returned.
If the search gives an invalid object or NULL we proceed in the session creation, creating and adding the session object in the sessions list and calling add_session_info(). Finally we release the spinlock.
The original flags will be modified by removing the O_RDONLY and O_WRONLY in favor of O_RDWR, since we will always read and write on this file. In this way we preserve the effects of the O_EXCL flag if specified from userspace.
References add_session_info(), delete_session(), delete_session_rcu(), NO_FD, open_file(), search_session(), sessions, sessions_lock, and VALID_NODE.
Referenced by create_session().
open_file()
int open_file (const char * pathname, int flags, mode_t mode, int fd_needed, struct file ** file)
Opens a file from kernel space.
Parameters
[in] pathname String that represents the file location and name and must be in kernel memory
[in] flags Flags that will regulate the permissions on the file.
[in] mode The permissions to apply to newly created files.
[in] fd_needed If set to NO_FD the file descriptor for the openend file will not be assigned (used only when we are opening original files).
[out] file pointer to the file struct of the opened file.
Returns
The file descriptor on success, the error code or NO_FD if no file descriptor was requested.
This function will open the file at the specified pathname and then associate a file descriptor to the opened file. If the O_CREAT flags is specified the permissions for the newly created file will be defined by the mode parameter or, if this is -1 by DEFAULT_PERM. If fd_needed is set to NO_FD then the opened file won't have a file descriptor associated.
References DEFAULT_PERM, and NO_FD.
Referenced by create_incarnation(), and init_session().
search_session()
struct session* search_session (const char * pathname, int filedes, pid_t pid)
Searches for a session with a given pathname, or with an incarnation with matching pid and file descriptor.
Parameters
[in] pathname The pathname that identifies the session.
[in] filedes The file descriptor of an incarnation.
[in] pid The pid of the process that owns the incarnation.
Returns
A pointer to the found session or NULL.
Searches, by navigating the sessions rcu list, a session which matches the given pathname. If pathname is NULL, filedes is differrent from NO_FD and pid is differrent from NO_PID then it searches for the session that contains an incarnation with the corresponding pid an file descriptor. While walking the sessions list the reference counter counter of any session currently inspected, refcount, will be incremented. If the session is not the one we are looking for then refcount will be decremented before inspecting the next session. If a session is invalid it will be skipped.
Additionally while walking the incarnation list of a session we grab the sess_lock in read mode, to avoid that a concurrent process modifies the list while we are walking it. When we finish walking the list we will release the lock.
References NO_FD, NO_PID, sessions, and VALID_NODE.
Referenced by close_session(), create_session(), and init_session().