SessionFS - A session based VFS wrapper: src/kmodule/session_info.h File Reference
session_info.h File Reference
Handles the kobjects for the session manager, part of the Session Information submodule. This file is used to create and manage kobjects for the session manager.
#include <linux/kobject.h>
#include <linux/types.h>
#include "session_types.h"
Macros
#define ATTR_GROUP_NAME "info"
Each attribute group has the same name, but different attributes according to the parent kobject.
#define SESS_KOBJ_NAME "SessionFS_info"
The name of the Kobject representing the session manager in SysFS.
Functions
int add_incarnation_info (struct sess_info *parent_session, struct kobj_attribute *incarnation, pid_t pid, int fdes)
Adds a new kobject attribute representing an incarnation.
int add_session_info (const char *name, struct sess_info *session)
Adds a new kobject representing an original file, under the SessionFS kobject.
int init_info (struct kobject *device_kobj)
Initializes the SessionFS kobject with general information about the running sessions.
void release_info (void)
Removes the SessionFS information from the device provided in init_info().
void remove_incarnation_info (struct sess_info *parent_session, struct kobj_attribute *incarnation)
Removes the kobject attribute incarnation from a kobject.
void remove_session_info (struct sess_info *session)
Removes a session kobject.
Detailed Description
Handles the kobjects for the session manager, part of the Session Information submodule. This file is used to create and manage kobjects for the session manager.
Function Documentation
add_incarnation_info()
int add_incarnation_info (struct sess_info * parent_session, struct kobj_attribute * incarnation, pid_t pid, int fdes)
Adds a new kobject attribute representing an incarnation.
Parameters
[in] parent_session The session which has generated the incarnation, represented by a struct sess_info.
[in] incarnation The incarnation to be added.
[in] pid The pid of the process that owns the incarnation.
[in] fdes The file descriptor that identifies the incarnation in the process.
Returns
0 on success, or an error code.
By adding a new incarnation we increment active_sessions_num and active_incarnations_num for the given session, represented by its sess_info member, also, a kobject attribute is added to the given session that has the process pid as filename and contains the process name. Finally the reference counter of the given session is also incremented.
The format of the file found on SysFS [pid]_[file descriptor], to allow the same process to have the process open the same file multiple times.
References KERN_OBJ_PERM, proc_name_show(), and sessions_num.
Referenced by create_incarnation().
add_session_info()
int add_session_info (const char * name, struct sess_info * session)
Adds a new kobject representing an original file, under the SessionFS kobject.
Parameters
[in] name The name of the created kobject.
[in,out] session The information on the session, represente by a struct sess_info.
Returns
a struct kobject* on success, null if the kobject hasn't been created or an error code.
We add a new folder in sysfs which is represented by the given kobject. The session kobject, represented by the sess_info member the session object will be created as a child of dev_kobj, and the dev_kobj reference counter will be incremented.
We also format the filename substituting '/' with '-'.
Finally, initialize the number of incarnations as a kobj_attribute.
References active_incarnations_num_show(), dev_kobj, and KERN_OBJ_PERM.
Referenced by init_session().
init_info()
int init_info (struct kobject * device_kobj)
Initializes the SessionFS kobject with general information about the running sessions.
Parameters
[in] device_kobj The SessionFS char device kernel object, in which contains the info on all sessions.
Returns
0 on success, an error code on failure.
We add an attribute called active_sessions_num to the SessionFS device kernel object, which is only readable and its content is the number of active sessions.
References dev_kobj, kattr, and sessions_num.
Referenced by init_device().
release_info()
void release_info (void)
Removes the SessionFS information from the device provided in init_info().
We remove the 'active_sessions_num' attribute from the device
References dev_kobj, and kattr.
Referenced by release_device().
remove_incarnation_info()
void remove_incarnation_info (struct sess_info * parent_session, struct kobj_attribute * incarnation)
Removes the kobject attribute incarnation from a kobject.
Parameters
[in] parent_session The session which has generated the incarnation, represented by a struct sess_info.
[in] incarnation The incarnation to be added.
By removing an incarnation we decrement active_sessions_num and active_incarnations_num for the given session, represented by its sess_info member. Also, the kobject attribute that has the process pid as filename and contains the process name is removed from the given session. Finally the reference counter of the given session is also decremented.
References sessions_num.
Referenced by clean_manager(), and delete_incarnation().
remove_session_info()
void remove_session_info (struct sess_info * session)
Removes a session kobject.
Parameters
[in] session the information on the session to be removed, represented by a struct sess_info.
Removes the entry corresponding to the given session, represented by its sess_info member, in the device SysFS folder. To do so we also remove the active_incarnations_num file of the given session and we decrement the reference counter of the device session kernel object.
References dev_kobj.
Referenced by clean_manager(), and close_session().