SessionFS - A session based VFS wrapper: src/demo/userspace_test.c File Reference
userspace_test.c File Reference
Userpsace program that will test the kernel module using the libsessionfs.c shared library.
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "../shared_lib/libsessionfs.h"
Macros
#define DEFAULT_PERM 0644
Permissions to be used when calling open()
Functions
int change_sess_path (char *path)
Use libsessionfs APIs to change the session path to path.
void fork_test (void)
Test file semantic with a session opened when forking.
void func_test (int files_max, char *base_fname)
A general functionality test.
int main (int argc, char **argv)
Testing of the kernel module.
void sess_change_test (void)
Test the semantic of sessions when the session path has changed.
Detailed Description
Userpsace program that will test the kernel module using the libsessionfs.c shared library.
It will "simulate" a general use-case in which the module can be used, by operating on a pseudorandom number of files with a pseudorandom number of processes.
Function Documentation
change_sess_path()
int change_sess_path (char * path)
Use libsessionfs APIs to change the session path to path.
Parameters
[in] path The path in which the session path should be changed.
Returns
0 or -1 in case of error. (errno is set by libsessionfs functions).
This utility function uses get_sess_path() and write_sess_path() to read the current session path, change it and display the results to the user, testing the session path change feature.
References get_sess_path(), and write_sess_path().
Referenced by main(), and sess_change_test().
fork_test()
void fork_test (void)
Test file semantic with a session opened when forking.
We open a file called fork_test.txt with session semantic then we execute the write test without appending done in func_test() on this file with both child and father processes. This is done to see if using session preserves the original semantic of the read, write and llseek functions. We can expect that one of the two processes will fail some operations on the file, since they have an intentional race condition on closing.
References close(), DEFAULT_PERM, O_SESS, and open().
Referenced by main().
func_test()
void func_test (int files_max, char * base_fname)
A general functionality test.
Parameters
[in] files_max The number of files to be used during the test.
[in] base_fname The string used to begin the filename of all the used files.
This function will test that all the features of the module are functional by simulating the common usage pattern that a single process could have, for a random number of files that goes from 0 to files_max. In detail we execute the following operations for each file:
read the active_sessions_num pseudofile;
we can sleep at random for 1 second, to give the other process, if any, a chance to override the incarnation;
open the file with the O_SESS flag;
we check active_sessions_num pseudofile;
we read active_incarnations_num and the file with our pid for each session we have created to ensure that they return meaningful values;
we test write, read and lseek writing a random number of bytes from 0 to 1MB, by writing the pid serveral times:
before writing we decide at random to overwrite the file or to append our contents, to have a chance to see different pids in the original file;
we write the process pid;
we seek back to where we have written the last pid;
we read what we have written;
we check that there aren't mismatches;
we seek to the beginning, middle and end of the file;
we sleep for 1 second at random, to have some files born from the same incarnation in the concurrent test;
we can close the opened file or leave it open at random to test how the module handles session with a dead owner;
we check active_sessions_num pseudofile;
References close(), DEFAULT_PERM, O_SESS, and open().
Referenced by main().
main()
int main (int argc, char ** argv)
Testing of the kernel module.
Parameters
[in] argc Number of the given arguments, 3 is expected.
[in] argv The arguments given to the file; we expect two arguments, the maximum number of processes to be used in the test followed by the maximum number of files to be used by each process.
We spawn a number of processes from 1 to the number given as first parameter, then in each child process we change the session path to the current directory using change_sess_path(), we execute func_test(), sess_change_test() and fork_test(). If the maximum number of processes used is 1 then all the files created by func_test() have a filename that starts with the single_process string, otherwise with the multi_process string.
To be able remove the kernel module we need to power down the SessionFS_dev device, using the dedicated ioctl as the last operation on the device.
References change_sess_path(), device_shutdown(), fork_test(), func_test(), and sess_change_test().
sess_change_test()
void sess_change_test (void)
Test the semantic of sessions when the session path has changed.
We change the session path to the current directory, then we open a file with O_SESS, in the current directory. Afterwards we change the session path to /mnt and we open a file with O_SESS again in the current directory. Then we close both files. The filename of the files created starts with the sess_change_test string.
References change_sess_path(), close(), DEFAULT_PERM, O_SESS, and open().
Referenced by main().